# Generated by Django 4.1.7 on 2023-04-01 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('10ee250d-c5f7-4028-9e1f-4143867450d1'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_sender', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('7fded50f-fbec-455b-b8e8-5e8bddd9e7e9'), editable=False, primary_key=True, serialize=False)),
                ('notification_via', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('user_uuid', models.UUIDField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('context', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
